- Add routine in configure script so to not destroy existing   installation and plugins

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,25 @@
+#!/bin/bash
+
+echo 
+echo "This script will install the latest version of Wordpress in "wordpress" directory";
+echo 
+echo 
+
+if [ -d "./wordpress" ]
+then
+    echo "wordpress directory already exist... aborting";
+    exit 1;
+fi
+
 wget https://wordpress.org/latest.zip
 unzip *.zip
 rm *.zip
 
+echo "This will replace the content of ./plugins and ./themes"
+read -p "Are you sure? " -n 1 -r
+echo 
+if [[ $REPLY =~ ^[Yy]$ ]]
+then
+    cp -fR wordpress/wp-content/plugins/* plugins/
+    cp -fR wordpress/wp-content/themes/* themes/
+fi
